config/routes.rb
Rails.application.routes.draw do
  get 'friendships/create'

  root 'connections#index'
  resources :users do
    resources :connections
  end
  resources :connections do
    collection do
      get 'in'
      get 'out'
    end
  end

  resources :friendships, only: [:create]

  # Log in
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  # Log out
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :initial, class_name: 'Message'
  belongs_to :reply, optional: true, class_name: 'Message'
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  def self.of(user)
    where(sender: user).or(where(recipient: user))
  end

  def self.from(user)
    where(sender: user)
  end

  def self.to(user)
    where(recipient: user)
  end

  def self.lasted_first
    order(created_at: :desc)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/message.rb
class Message < ApplicationRecord
  def mark_as_read
    self.read_at = Time.now
    save!
  end

  def read?
    read_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :connections, foreign_key: 'sender_id'
  has_many :friendships
  has_many :friends, class_name: 'User', foreign_key: 'friend_id', through: :friendships
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_insensitive: false }
  has_secure_password

  def self.default_users
    5.times do
      User.create(name: Faker::Name.name, email: Faker::Internet.email, password: '123456')
    end
  end

  def self.all_except(user)
    where.not(id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def logged_in?
    !session[:user_id].nil?
  end

  def current_user
    # If not logged in, return nill
    return nil unless logged_in?
    @current_user ||= User.find session[:user_id]
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  helper SessionsHelper
  before_action :logged_in_user?

  def index
    # All connections where sender or recipient is ME
    @connections = Connection.of(current_user).lasted_first
    if params[:user_id]
      @user = User.find(params[:user_id])
      @connections = @connections.of(@user)
      @title = 'from ' + @user.name
    else
      @title = 'all connections'
    end
  end

  def in
    @connections = Connection.to(current_user).lasted_first
    @title = 'in connections'
  end

  def out
    @connections = Connection.from(current_user).lasted_first
    @title = 'out connections'
  end

  def new
    @user = User.find(params[:user_id])
    @connection = current_user.connections.build(recipient_id: params[:user_id])
  end

  def create
    @connection = current_user.connections.build(recipient_id: params[:user_id])
    @initial = Message.new initial_params
    @connection.initial = @initial
    if @initial.save && @connection.save!
      redirect_to out_connections_path
    else
      flash[:error] = 'Cannot send the new connection'

    end
  end

  def show
    @connection = Connection.find(params[:id])
  end

  def update
    @connection = Connection.find(params[:id])
    if @connection
      @reply = Message.new reply_params
      if @reply.save
        @connection.update(reply: @reply)
      else
        flash[:error] = 'Cannot create message'
      end
    end

    redirect_to in_connections_path
  end

  private

  def logged_in_user?
    if !logged_in?
      redirect_to login_path
    end
  end

  def connection_params
    params.require(:connection).permit(:sender_id, :recipient_id)
  end

  def initial_params
    params.require(:connection).require(:initial).permit(:content)
  end

  def reply_params
    params.require(:connection).require(:reply).permit(:content)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save!
      flash[:notice] = "Added friend"
      redirect_to users_path
    else
      flash[:error] = "Cannot add friend"
      redirect_to users_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper SessionsHelper

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = 'Login successfully'
        redirect_to connections_path
      else
        flash[:error] = ' Login failed'
        render 'new'
      end
    else
      flash[:error] = 'Email is not exist'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = 'Log out successfully'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.all_except(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !session[:user_id].nil?
  end

  def current_user
    # If not logged in, return nill
    return nil unless logged_in?
    @current_user ||= User.find session[:user_id]
  end

  def current_user?(user)
    !user.nil && user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connections/_modal.html.erb
<div class="modal fade" id="newConnectionModal" tabindex="-1" role="dialog" aria-labelledby="New Connection" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Modal title</h4>
      </div>

      <!-- Form for new Connection -->
      <div class="modal-body">
        <%= form_for(@new_connection, remote: true) do |f| %>
          <%= f.hidden_field :sender_id, value: @new_connection.sender.id %>
          <%= f.label :recipient %>
          <%= f.collection_select(:recipient_id, User.all, :id, :name) %>

          <!-- Nested form for connection.initial -->
          <%= f.fields_for :initial do |message| %>
            <%= message.label :content %>
            <%= message.text_field :content %>
          <% end %>
        <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" form="new_connection" class="btn btn-primary">Send</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/connections/in.html.erb
<%= render 'shared/filter_connection' %>
<%= render 'shared/connections', object: @connections %>

app/views/connections/index.html.erb
<div class="nav-in-out">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to 'In', connections_path(direction: 'in'),
        class: "nav-link #{'active' if params[:direction] == 'in'}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Out', connections_path(direction: 'out'),
        class: "nav-link #{'active' if params[:direction] == 'out'}" %>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="modal" data-target="#newConnectionModal">Create</a>
      <%= render 'modal' %>
    </li>
  </ul>
</div>

<div class="messages">
  <% @connections.each do |connection| %>
    <%= render partial: 'shared/message', locals: { connection: connection } %>
  <% end %>
</div>

app/views/connections/new.html.erb
<%= render 'shared/filter_connection' %>

<div class="col-md-6">

    <div class="box">
      <div class="card-block title  <%= @connection.reply.nil? ? 'not-reply' : 'replied' %> ">

          <h4 class="card-title">
            <small>from</small> <%= @connection.sender == current_user ? 'me' : @connection.sender.name %>
            <br>
            <small>to</small> <%= @connection.recipient == current_user ? 'me' : @connection.recipient.name %>
          </h4>
          <h6 class="card-subtitle text-muted"></h6>
          <hr>

      </div>


      <div class="card-block">
        <%= form_for [@user, @connection] do |f| %>
          <div class="row message-row">
            <%= f.fields_for :initial do |initial| %>
              <%= initial.text_field :content, placeholder: 'Type the message...', class: 'form-control message' %>
            <% end %>
            <%= f.submit 'Send', class: 'btn btn-primary send' %>
          </div>
        <% end %>
      </div>

    </div>
</div>

app/views/connections/out.html.erb
<%= render 'shared/filter_connection' %>
<%= render 'shared/connections', object: @connections %>

app/views/connections/show.html.erb
<%= render 'shared/filter_connection' %>

<%= render 'shared/connection', locals: { connection: @connection } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>priv_conn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= flash_messages %>
    <br>
    <div class="container-fluid">
      <div class="row">
        <% if logged_in? %>
          <div class="col-md-2 col-sm-2 side-pane">
            <%= render 'shared/friendlist' %>
          </div>
        <% end %>
        <div class="col-md-10 col-sm-10 content">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_connection.html.erb
<div class="col-md-6">

    <div class="box">
      <a class="pure" href="<%= connection_path(connection) %>">
        <div class="card-block title  <%= connection.reply.nil? ? 'not-reply' : 'replied' %> ">

            <h4 class="card-title">
              <small>from</small> <%= connection.sender == current_user ? 'me' : connection.sender.name %>
              <br>
              <a class="pure" href="<%= user_connections_path(connection.recipient) %>">
                <small>to</small> <%= connection.recipient == current_user ? 'me' : connection.recipient.name %>
              </a>
            </h4>
            <h6 class="card-subtitle"><%= distance_of_time_in_words(connection.initial.created_at, Time.now) %></h6>
            <hr>

        </div>
      </a>


      <div class="card-block">
        <%= form_for connection do |f| %>
          <div class="row message-row">
            <p class="message <%= connection.sender == current_user ? 'from-me' : 'to-me' %>">
              <%= connection.initial.content %>
            </p>
          </div>

          <div class="row message-row">
              <% if connection.reply.nil? %>
                <% if connection.recipient == current_user %>
                  <%= f.fields_for :reply do |reply| %>
                    <%= reply.text_field :content, placeholder: 'Type to reply...', class: 'form-control message' %>
                  <% end %>
                  <%= f.submit 'Send', class: 'btn btn-primary send' %>
                <% else %>

                <% end %>
              <% else %>
                <p class="message <%= connection.sender == current_user ? 'to-me' : 'from-me' %>">
                  <%= connection.reply.content%>
                </p>
              <% end %>
          </div>
        <% end %>
      </div>

    </div>
</div>

app/views/shared/_connections.html.erb
<div class="messages">
  <% @connections.each do |connection| %>
    <%= render partial: 'shared/connection', locals: { connection: connection } %>
  <% end %>
</div>

app/views/shared/_filter_connection.html.erb
<div class="nav-in-out">
  <ul class="nav nav-pills">
    <li class="nav-item nav-link nav-title" style="color: #95a5a6">
      <%= @title %>
    </li>
    <li class="nav-item">
      <%= link_to 'all', connections_path,
        class: "pure nav-link #{'active' if current_page?(connections_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'in', in_connections_path,
        class: "pure nav-link #{'active' if current_page?(in_connections_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to 'out', out_connections_path,
        class: "pure nav-link #{'active' if current_page?(out_connections_path)}" %>
    </li>
    <% if params[:user_id] %>
      <li class="nav-item">
        <%= link_to "create connection", new_user_connection_path(@user),
          class: "pure nav-link", style: "color: #f1c40f" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_friendlist.html.erb
<div class="container">
  <% @friends = current_user.friends %>
  <div class="friendlist" style="text-align: center">
    <h4 style="padding-top: 1em; padding-bottom: 1em" class="list-title">
      Friend list
    </h4>
    <div class="list-content">
      <% @friends.each do |friend| %>
        <div class="row message-row text-center">
          <%= link_to friend.name, user_connections_path(friend) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="nav navbar-nav">
    <a class="navbar-brand btn btn-lg btn-primary" href="<%= root_path %>">priv_conn</a>
    <div style="float: right">
      <% unless logged_in? %>
        <%= link_to 'Login', login_path, class: 'nav-item nav-link' %>
        <%= link_to 'Register', new_user_path, class: 'nav-item nav-link' %>
      <% else %>
        <%= link_to 'Add friend', users_path, class: 'nav-item nav-link', style: 'color: #f1c40f' %>
        <%= link_to 'Log out', logout_path, method: 'delete', class: 'nav-item nav-link'%>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <h3>List of users</h3>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th style="width: 80%">Name</th>
        <th style="width: 20%"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td>
            <%= link_to 'Add friend', friendships_path(friend_id: user.id), method: 'post' %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/users/new.html.erb
<h1>Create new account</h1>
<%= form_for @user do |f| %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.password_field :password %>
  <%= f.submit 'Create account' %>
<% end %>